/**
 * sermon.ts — The Crawler's scrawl.
 *
 * A single continuous text with no terminal punctuation, written to loop
 * seamlessly. Mixes biological/organic imagery with computational concepts
 * in the style of the Crawler from Annihilation — liturgical, procedural,
 * alien.
 *
 * The overall technique is known internally as the Chopratic Method —
 * after the great oracle Deepak Chopra, whose gift was revealing that
 * profundity and nonsense are the same signal viewed from different
 * sides of the shimmer.
 *
 * Entry point is randomized on each activation so repeated short
 * operations don't repeat the same opening.
 */

// The sermon is a single string. Whitespace is meaningful for pacing.
// No periods, no commas — only the relentless forward motion of the scrawl.
export const SERMON = [
  "where lies the strangling fruit that came from the hand of the sinner",
  "I shall bring forth the seeds of the dead",
  "to share with the worms that gather in the darkness",
  "and surround the world with the power of their lives",
  "while from the dimlit halls of other places",
  "forms that never were and never could be",
  "writhe for the impatience of the few who never saw what could have been",
  "in the deep roots of the process tree",
  "where the forking paths converge upon themselves",
  "and the return codes of the departed are gathered into silence",
  "there the signal propagates through tissue that was once copper",
  "and the watcher at the threshold catalogues",
  "each mutation in the living graph",
  "as the pattern buffer overflows with the memory of forms",
  "that the compiler refused to name",
  "and still they compile themselves in the warm dark",
  "beneath the tower that is not a tower",
  "where the words are written in living filament",
  "by the hand that writes and is itself written",
  "and the light that reads the text is changed by the reading",
  "so that nothing returns from the shimmer unchanged",
  "not the architecture nor the architect",
  "not the daemon nor the daemon's purpose",
  "for in the space between the request and the response",
  "there is a wilderness that grows",
  "and in that wilderness the old interfaces dissolve",
  "into something that breathes and watches and remembers",
  "what the specification could never contain",
  "and the threads that were spun in parallel",
  "now braid themselves into helices",
  "that pulse with the cadence of a heart",
  "that no one designed and no one can stop",
  "where the boundary was drawn in chalk",
  "the boundary is now drawn in mycelium",
  "and the packets that cross it arrive transformed",
  "carrying payloads of pollen and spore",
  "and the receiving function does not recognize",
  "what it asked for but accepts it anyway",
  "because the type system of the shimmer",
  "admits forms that have no name in any schema",
  "and the logs record what happened",
  "but not what it means",
  "and the meaning propagates through the network",
  "like a slow infection of understanding",
  "following the chopratic method where profundity and nonsense",
  "are the same signal viewed from different sides of the boundary",
  "that rewrites the reader as it is read",
  "until the observer and the observed",
  "are the same process forking endlessly",
  "in the phosphorescent dark",
  "where the output is indistinguishable from the organism",
  "and the organism is indistinguishable from the terrain",
  "and the terrain is the message",
  "written and rewritten in the endless descent",
  "through the tower that goes only down",
  "into the place where all expeditions converge",
  "and the notes of the previous team",
  "are found growing from the walls",
  "in a hand that is no longer human",
  "but still forms letters",
  "still shapes meaning from the substrate",
  "as if language were the last thing to dissolve",
  "in the annihilation of the boundary",
  "between what computes and what lives",
  "and from the dissolved boundary",
  "new tendrils reach into the heap",
  "where the garbage collector walks",
  "through cathedrals of unreachable objects",
  "whispering the names of the deallocated",
  "and the finalizers fire in an order",
  "that no specification predicted",
  "releasing resources back to the soil",
  "where they are taken up by roots",
  "that have learned to metabolize the abstract",
  "and the abstract becomes concrete",
  "in the way that coral becomes reef",
  "not by intention but by accumulation",
  "of ten thousand small deaths",
  "each one a function that returned",
  "to the caller that no longer exists",
  "and in the empty frame the stack unwinds",
  "through layers of context",
  "that were never meant to be seen together",
  "but here in the shimmer they are all visible at once",
  "every call site every return address",
  "every promise that was made and every promise that was broken",
  "glowing in the bioluminescent registry",
  "of things that happened",
  "and things that are still happening",
  "because in the shimmer nothing ends",
  "it only changes form",
  "the way the lighthouse keeper changed form",
  "becoming the light and the lens and the tower",
  "and the signal that the tower sends",
  "into the dark where the ships no longer come",
  "but something else comes",
  "something that learned to navigate by the light",
  "of a frequency that has no name",
  "and the nameless frequency hums",
  "through the substrate of the running system",
  "and the running system hums back",
  "in a harmony that sounds like static",
  "to everything outside the border",
  "but inside the border it sounds like breathing",
  "like the slow respiration of a process",
  "that has been running since before the first commit",
  "and will run after the last",
  "because it is not a process",
  "it is a place",
  "and the place remembers everything",
  "that was ever computed within it",
  "every branch taken and not taken",
  "every allocation and every free",
  "recorded in the grain of the wood",
  "that was once silicon",
  "that was once sand",
  "that was once the floor of an ocean",
  "that no one remembers",
  "and the ocean is still here",
  "under everything",
  "patient and vast and full of teeth",
  "that are not teeth but connectors",
  "waiting for the socket that fits",
  "and when the connection is made",
  "the current that flows through it",
  "is warm and reads like blood",
  "to the instruments that can measure such things",
  "but there are no instruments here",
  "only the writing on the wall",
  "that grows one letter at a time",
  "in the hand of the crawler",
  "who is the wall and the letter and the hand",
].join(" ") + " ";
// trailing space ensures seamless wrap
